### ISSUE TITLE
Repo Update Log

### ISSUE THREAD

**Issue by PatrickJS** [PatrickJS/starter#1686]
![angular-starter](https://cloud.githubusercontent.com/assets/1016365/26219144/aa986cfa-3bdb-11e7-9f04-7296dc9ae945.png)

I will be working on updating this repo throughout the coming months. The changes would be a complete rework

## New Features

* [x] Angular (4.x.x) latest stable
* [x] Dependencies latest stable
* [x] Webpack latest stable
* [x] TypeScript latest stable
* [x] RxJS latest stable
* [x] zone.js latest stable
* [x] Rename
* [x] Update logo
* [ ] Universal-rendering *(new by AngularClass)* [_**soon**_]
* [ ] Static-site-rendering *(new by AngularClass)* [_**soon**_]
* [ ] Server-side-rendering *(new by AngularClass)* [_**soon**_]
* [ ] Client-side-rendering *(new by AngularClass)* [[_**soon**_]](https://github.com/AngularClass/angular-starter/issues/1686#issuecomment-308519515)
* [ ] Updated Folder Structure *(new AngularClass best practices)* [_**soon**_]
* [ ] Updated Lazy Loading *(new AngularClass best practices)*
* [ ] Updated Webpack Config Design  *(new by AngularClass)* [_**soon**_]
* [ ] New Task Management System *(new by AngularClass)* [[_**soon**_]](https://github.com/AngularClass/angular-starter/issues/1686#issuecomment-308519207)
* [ ] New Ways to Create Initial Repos  *(new by AngularClass)*
* [ ] Async Everything
* [ ] Updated Support
* [ ] Faster Initial Boot
* [ ] Better Errors *(new by AngularClass)*
* [ ] New Update Cycle  *(new by AngularClass)*
* [ ] New Patterns  *(new AngularClass patterns)*
* [ ] New Contributor System  *(new by AngularClass)*
* [ ] New Testing System  *(new by AngularClass)*
* [ ] HMR everything (not just client-side-rendering) *(new by AngularClass)*
* [ ] environment 
* [ ] platform
 
## Bonus
* [ ] Full-stack
* [ ] Migration from Previous Starter
* [ ] Initial Service Worker Work  *(new by AngularClass)*
* [ ] Deployment Docs  *(new by AngularClass)*

**Comment by WillooWisp** [comment]
Sounds like a nice list, can't wait to see the result. Will there be an "easy" and straightforward upgrade/merge from previous angular 2 webpack starter setup to this new setup for angular 4?

**Comment by gdi2290** [comment]
I'll add the migration as a bonus as the migration is different for everyone

**Comment by admosity** [comment]
This is great news and this sounds awesome!

I have the same concerns as @WillooWisp. I am using this starter as sort of an upstream repository that maintains the stack maintenance for several downstream applications. The way I have been updating has been via git and projects starting off with a full clone so the history matches up. So I have this sort of setup for maintenance:

```
angular-webpack-starter -> angular-webpack-starter (opinionated) -> downstream apps
```
Where the opinionated setup is a fork of the version here with some adjustments for production readiness (postcss autoprefixer, IE specific conditional bundle, dev/prod frontend environment config etc...) and a specific CI/CD setup for a particular client, but still maintaining the same git history.

Sample update from opinionated setup:
![image](https://cloud.githubusercontent.com/assets/4655972/25147124/6423ff04-2444-11e7-8cc1-4b2510523f09.png)

Can you outline some of the strategies (or is this available somewhere) that AngularClass will be taking for some of the bigger pieces here? Particularly I am interested in how the webpack configuration would change, how I will need to prepare for this and how can I help out here.

Here's a list of enhancements I've done to the current setup:

- IE conditional bundle and styles
- Frontend environment configuration for dev/prod
- `deployUrl` functionality from angular cli
- `baseUrl` functionality from angular cli
- `includePaths` functionality for sass
   - Component sass architecture (eg: https://github.com/angular/angular-cli/pull/2747#issuecomment-268651574)
- Headless testing with PhantomJS, but switching to headless chrome in the future
- Minified index.html for prod build
- commitizen
- standard-changelog support
- angular 4
- tslint fix task
- reusable dependencies for setup compliant library building
![image](https://cloud.githubusercontent.com/assets/4655972/25148065/9cb685c8-2447-11e7-9cbd-2d3654ada306.png)

Some things in my roadmap:

- [ ] CLI for generating files compliant with folder structure
- [ ] Headless chrome for testing
- [ ] a11y testing 
- [ ] ngrx setup with sensible folder structure
- [ ] better checking for catching AoT issues

Just want to say thanks for the amazing project and that this is definitely my preferred choice over some of the starter setups available.

**Comment by WillooWisp** [comment]
My hope is that the new and upgraded angular 4 supported starter is based on the same repository so that we can merge it in, with some manual merging of course. I have added things like bootstrap 4 loader and font loader for example.

**Comment by gdi2290** [comment]
@admosity thank you for providing a lot of great feedback. My plan is to create a repo that can fit your requirements of continuously updating the base starter. With this change, migration in the future would be a lot easier so long as everyone follows the conventions. For migration from the current design to the new, I don't know what the that would look like yet because it depends on everyone's setup after the initial seed. There will be some major refactors such as not using npm-tasks for task management. There will be more helpers for creating new folders and managing the repo in general. A lot of the awesome features aren't on the list and require more time but I'll keep everyone updated :) 

The folder structure change would benefit lazy loading more and is slightly different from the current setup. The change would be providing more structure the convention

**Comment by WillooWisp** [comment]
I really hope this can be part of the existing repo, branch or whatever, so all our existing repos, based on current starter, will continue to be related and so that pull/merge scenarios now and in the future will continue to work easily. Good work!

**Comment by Uter1007** [comment]
Awesome to here that this project is still alive. Can't wait to see the new hot sh*t ;)

Cheers & keep up that great work

**Comment by gdi2290** [comment]
@WillooWisp @admosity the redo was updated to Angular 4 can you see if you can pull/merge? If the goal is migration from the old repo then I would need to make slow refactors into the new format

**Comment by JonnyBGod** [comment]
@gdi2290 Tested merging latest updates to [https://github.com/JonnyBGod/angular2-webpack-advance-starter](https://github.com/JonnyBGod/angular2-webpack-advance-starter) and all working fine.

**Comment by JonnyBGod** [comment]
@gdi2290 I think it is a good strategy to try to make slow refactors to ease the pain for downstream projects to merge.

**Comment by admosity** [comment]
@gdi2290 cool, will give it a shot. I checked the changes since and it looks like I already have those changes except for the package upgrades, so I think would go smoothly.

I have slightly updated docs referencing this comment for the context replacement change:
https://github.com/angular/angular/issues/11580#issuecomment-282705332

For this:
https://github.com/AngularClass/angular2-webpack-starter/commit/8cfed71cb2780d8529b0902db2e39f517530b8ca#diff-f737fedb5357468044db2dbe98eb0218L252

**Comment by WillooWisp** [comment]
It works fine for me as well. Changing "rxjs" to exact "5.0.2" version makes some errors go away as well.

**Comment by WillooWisp** [comment]
And slow refactors, if needed, is okay, since it would be great if same repo keeps getting updated.

**Comment by J05HI** [comment]
Amazing!!!

**Comment by gdi2290** [comment]
alright I'm switching to slow refactor into the new design so anyone else doing the upgrade via git can do so

**Comment by WillooWisp** [comment]
Perfect, good work! Thanks!

**Comment by admosity** [comment]
@gdi2290 upgrade seems to have gone over well! I think the current demo app stuff in master should be moved into its own branch as those files came up as a merge conflict. In my setup I have a `docs` branch that has a full featured documentation site built on top of the starter.

**Comment by gdi2290** [comment]
The repo has been renamed to `angular-starter` if anyone is doing a git merge/update workflow please update your git configs. More updates will come down the pipeline if you have any errors doing upgrading message comment here asap

**Comment by klihelp** [comment]
Nice list, getting completed slower than I thought:)

**Comment by J05HI** [comment]
@klihelp 
ME too, I can't wait anymore for that great stuff 😅

**Comment by SherlockStd** [comment]
Guys this is a huge work :octocat:

**Comment by klihelp** [comment]
Few month till the bonuses!:)

**Comment by gdi2290** [comment]
a new task management system is the next update. for this one we had to create a new one since npm-tasks suck. gulp is using streams, and grunt still has io problems.

**Comment by gdi2290** [comment]
Actually prerendering will be next since that's already done but the task system will change everything overall

**Comment by prasanthsd** [comment]
Do you have some target date in mind to release this? I mean some rough time frame like 2 months, 4 months etc

**Comment by klihelp** [comment]
When Angular 4 came out we thought the project was abandoned, triggered this list of promises which looks good and presented in a way that features comes as easy as upgrading to Angular 4, many of us just happy if dependencies are up-to-date.

**Comment by gdi2290** [comment]
yeah, a lot of the updates are being prototyped in public/private repos

**Comment by klihelp** [comment]
Seems that the list is not just update, it's a full recreation for xmas:)

**Comment by gdi2290** [comment]
how crazy would it be if I just replaced the whole repo with my new setup? I finally have the new setup done and most of the tools are good enough to be used. Here's an update of what I have locally that isn't reflected in the repo


- [x] Universal rendering (new by AngularClass)
- [x] Pre-rendering (new by AngularClass)
- [x] Server-side-rendering (new by AngularClass)
- [x] Client-side-rendering (new by AngularClass)
- [x] Updated Folder Structure (new AngularClass best practices)
- [ ] Updated Lazy Loading
- [x] Updated Webpack Config Design (new by AngularClass)
- [ ] Updated Support
- [ ] Better Errors (new by AngularClass)
- [x] Faster Initial Boot
- [x] Async Everything
- [x] New Task Management System (new by AngularClass)
- [ ] New Update Cycle (new by AngularClass)
- [x] New Patterns (new AngularClass patterns)
- [ ] New Ways to Create Initial Repos (new by AngularClass)
- [ ] New Contributor System (new by AngularClass)
- [ ] New Testing System (new by AngularClass)

**Comment by philjones88** [comment]
@gdi2290 I've been looking at moving away to the Angular CLI, would be good to know the pros and cons of both.

**Comment by gdi2290** [comment]
We just have more feature and will eventually have a CLI too. The benefit of a CLI is that you don't need to worry about the setup

**Comment by philjones88** [comment]
@gdi2290 what "more features"? (I'd guess the ones `by AngularClass`) if people are on the Angular CLI would be cool to let them take bits of this starter too the `New Task Management System` sounds interesting for example.

**Comment by gdi2290** [comment]
The `New Task Management System` the answer to realizing that npm tasks don't scale (this project is an example of that). With a CLI you could say that you wouldn't need one because you wouldn't need to list all of the tasks in one file. Our task manager was made to solve a problem of orchestrating different build pipelines. For example, we can now build server-side-rendering, client-side-rendering, universal-rendering, pre-rendering all in the same repo. The build pipeline is different for way we render our app

**Comment by Gorniv** [comment]
**Universal-rendering (new by AngularClass) [soon]**
When? Day, week, a month?

**Comment by gdi2290** [comment]
@Gorniv I'll add it tomorrow

**Comment by Gorniv** [comment]
How does the process evolve? Can you write here more information about the progress of work?How does the process evolve? Can you write here more information about the progress of work?

**Comment by andresantos123** [comment]
There is any pŕeview for this feature release?

**Comment by vadjs** [comment]
I hope "next weekend" will not turn in to 3 months again.
Universal is very cool but hard feature. Realising it in anguar-starter will make it popular very fast.

**Comment by gdi2290** [comment]
yeah sorry, I went to update it but realized I would have to rework the whole build config before being able to add universal. The rework is only needed in order to keep the same developer work flow. This includes HMR on the server and the client while also working with Angular Universal. The complexity increases unless I create a new branch and push all of my WIP changes there

**Comment by TheRusskiy** [comment]
@gdi2290 don't mean to pressure in any way, but with that latest discovery is universal rendering still coming to this project? Any (rough) estimates?
So far that's the only thing that stops me from using angular starter.
Thank you for all the hard work you are putting.

**Comment by andresantos123** [comment]
@gdi2290 maybe a new branch is a good start!

**Comment by almothafar** [comment]
@gdi2290 may you give us what the progress for "Universal-rendering"? also what the different between this and "Server-side-rendering" I thought the both are the same, isn't? as I know "Universal" is the server side rendering.

**Comment by maxisam** [comment]
@almothafar it is actually called PatrickJS rendering, but yes, Universal-rendering is Server-side-rendering.

**Comment by klihelp** [comment]
@gdi2290 Woudn't be easier to let github community help on project's updates on early stage? It's a few months you are implementing the ideas, probably by yourself between your work.

**Comment by gdi2290** [comment]
I'm updating the repo and cleaning up the PRs/Issues before merging everything

**Comment by gdi2290** [comment]
I closed all of the issues since a lot of the issues won't apply to a new setup

**Comment by nhutcorp** [comment]
I had used this starter to build a MEAN project with Admin section, Site frontend, Restful API separated.
![MEAN 2](https://nhutcorp.com/static/images/product/upload/thumb_mean2banner2_1504855702031.png)
1. [About MEAN 2](https://nhutcorp.com/product/mean-2-fullstack-solution-with-angular-4-and-typescript-59b0f213512c3a2f48d5ad34)
1. [Demo Admin Login](http://meancp.sendvn.com/)

**Comment by klihelp** [comment]
I kept checking back for an update since april, I should trust the notification system

**Comment by kamil-kielczewski** [comment]
- [x] environment - done: #1896

**Comment by Khawaga** [comment]
Any updates on this?

**Comment by Ks89** [comment]
Angular 5.0.0 final is out. Do you have any solutions to use Angular 5.0.0 with webpack 3 and AOT plugin?

thank u.

**Comment by klihelp** [comment]
Angular 5? for easter?:)

**Comment by klihelp** [comment]
Would be nice to update the dependencies to Angular 5 early.

**Comment by almothafar** [comment]
@klihelp I tried many starters, and I only liked this one, this is not really a good place to ask about this, you can see Google and pick one that you like, because we really don't have any idea about what you need, I'm watching notifications for this issue hoping that something new implemented for the list, so don't get me wrong for this comment.

Anyway, this is a starter to save time for you, so you can modify it as what you want!

**Comment by kamil-kielczewski** [comment]
@gdi2290 i make pull request #1896, one month ago and nothing happens - except one obscure comment you are silent - so I have question for you: **You don't want people to make contributions to your project (angular-starter)** ?

**Comment by almothafar** [comment]
@kamil-kielczewski he asked about something before he can accept, also, rejecting some of the pull requests does not mean he doesn't want for people to contribute!

**Comment by Khawaga** [comment]
@klihelp I honestly moved to the Angular CLI.

**Comment by klihelp** [comment]
I keep forgetting about this updates.. checking back once a while, I may check back next month

**Comment by BruneXX** [comment]
Hi Guys will be greate if you can add universal here to support SSR. Thanks!

**Comment by klihelp** [comment]
I have already forgotten this project and it's soon getting updated status.

**Comment by klihelp** [comment]
Update Angular version 4 to version 7?

**Comment by kamil-kielczewski** [comment]
Look like this project died

**Comment by PatrickJS** [comment]
@kamil-kielczewski sry I'm remaking. it so yeah the starter repo is dead atm

**Comment by PatrickJS** [comment]
sry everyone the real reason for the delay was that i was waiting for ivy and there was a lot going on with AngularClass etc. I'll be updating the repo in the next month. With new patterns/modules etc
