### ISSUE TITLE
@ngrx 4 integration?

### ISSUE THREAD

**Issue by colinskow** [PatrickJS/starter#1889]
[@ngrx](https://github.com/ngrx/platform) has become the golden standard for state management in Angular. This project is simple enough that it's not necessary, but it can be tricky to integrate correctly with HMR.

I've got it working perfectly in [angular-electron-dream-starter](https://github.com/colinskow/angular-electron-dream-starter). If you are interested @gdi2290 I can make a pull request. It simply replaces your generic state management with a single reducer and single action.

**Comment by supermarioim** [comment]
whats with this? it would be really useful to have ngrx included out of the box.
