### ISSUE TITLE
IE 11 Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by Kaffiend** [PatrickJS/starter#1893]
[* ] bug report

* **What is the current behavior?**
does not load in IE 11 after refresh. It only works for the initial load with `npm start`

* **What is the expected behavior?**
Load in IE 11 with refresh

- Angular version: 4.4.3
- Browser: IE 11
I've loaded the es6 polyfills and still doesnt work. 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by sen-yang** [comment]
I am having the same issue, the page will load fine if i select always refresh from server in the network tab in developer tools. Perhaps ie11 caching is not loading the polyfills correctly.

Although this issue doesn't occur in a fresh project.

**Comment by sen-yang** [comment]
Ok i think i solved it.
If you go into webpack.common.js and uncomment the part that says

Specify the correct order the scripts will be injected in
` 
      new CommonsChunkPlugin({
        name: ['polyfills', 'vendor'].reverse()
      }),
      new CommonsChunkPlugin({
        name: ['manifest'],
        minChunks: Infinity,
      }),`

this will load the polyfills before main.bundle.js.

**Comment by Kaffiend** [comment]
Great find @sen-yang, saves me some time, I haven’t had much time to look into it, with other matters pressing.

Ian Mackie
Lead Developer
Complete System Support, Inc.

**Comment by lanovoy** [comment]
Sorting of the chunks is handled by the HtmlWebpackPlugin 
`
chunksSortMode: function (a, b) {
          const entryPoints = ["inline","polyfills","sw-register","styles","vendor","main"];
          return entryPoints.indexOf(a.names[0]) - entryPoints.indexOf(b.names[0]);
},
`
Make sure the entry points are named correctly...
