### ISSUE TITLE
how to import js plugins like morrisjs?

### ISSUE THREAD

**Issue by rabpeter** [PatrickJS/starter#1895]
I got some problems when I'm using morris js plugins . how to import other js plugins when using this repo  for angular app basic structure?

**Comment by gabrielrb** [comment]
i´m watching for the same answer.
i´m trying to import toastr...
i´ve imported it in app.module.ts, but it doesn´t went to the main.bundle.

**Comment by leif2017** [comment]
i´m watching for the same answer.
