### ISSUE TITLE
String environment variable is undefined in .module.ts files after AoT build

### ISSUE THREAD

**Issue by almothafar** [PatrickJS/starter#1902]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
I want to ask about passing environment variable to module, as for example if I follow this document https://github.com/AngularClass/angular-starter/wiki/How-to-pass-environment-variables%3F
Then tried to user API_URL in module to initialize another module (as for example using angularfire2) the API_URL in AoT build is undefined

* **What is the current behavior?**
What ever I tried I get undefined, if I tried to export it from environment.ts like:

`export const ENV_API_URL: string = API_URL;
`

and use `ENV_API_URL` inside the module, it is printed as ` [object Object]`

The strange thing if I defined an object like full, and export it from environment like `const ENV_FIREBASE_CONFIG = FIREBASE_CONFIG;` this is working, but the problem now for the string like `API_URL`.

is the expected behavior?**
Getting the string value.

* **Please tell us about your environment:**

- Angular version: 4.4.x
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by kamil-kielczewski** [comment]
Here is [pull request](https://github.com/AngularClass/angular-starter/pull/1896) which solve problem with ENV variables

**Comment by almothafar** [comment]
On my version I changed some of the variables to get config from JSON file, as for example to get firebase config, to get title name and so on, it was helpful for dockerization and do the process with dev-test-stage then prod steps.

But the issue for me now is even the environment variable (not the one that I get from JSON) is returning with an object or undefined, anyway, I'll try to move my variable to JSON and see if it is working or not.

If yes, I'll send my pull request version :)

**Comment by kamil-kielczewski** [comment]
May be I not understand you well. Do you wanna get access to environment variables during building process? If so, my solution not solve this task - it's only read .env file in browser from server on runtime (on bootstrap - so after build process).

**Comment by stormit-vn** [comment]
I also facing this issue too...

I am using the .env file to store environment variables. Basically, it works during development. But when building AOT release, all variables not combined for when initializing a module at the root level, but it works when we get value from an injected service. I would like to know the root cause so that we can find a solution to fix this issue instead of using this fix. I am using **dotenv-safe** and **DefinePlugin** to define variables

```
// Load environment variables using dotenv-safe to apply https://12factor.net/ approach
const envVars = require('dotenv-safe').load({
    path: options.env === 'development' ? '.env' : `.env.${options.env}`,
    allowEmptyValues: true,

}).parsed;
const envMap = _.mapValues(envVars, item => JSON.stringify(item));
```

```
new DefinePlugin({
    'ENV': JSON.stringify(METADATA.ENV),
    'HMR': METADATA.HMR,
    'AOT': METADATA.AOT,
    'process.ENV': JSON.stringify(METADATA.ENV),
    'process.NODE_ENV': JSON.stringify(METADATA.ENV),
    'process.HMR': JSON.stringify(METADATA.ENV),
    'APP_CONFIG': envMap
}),
```

and here is how I use the variables to configure module at the root level
```
const oktaAuthConfig = {
    clientId: APP_CONFIG.OKTA_CLIENT_ID,
    issuer: `${APP_CONFIG.OKTA_BASE_URL}/oauth2/default`,
    redirectUri: APP_CONFIG.OKTA_REDIRECT_URL,
    scope: 'openid profile address email phone',
    onAuthRequired: onOktaAuthRequired
};


imports: [
    OktaAuthModule.initAuth(oktaAuthConfig),
],
```
