### ISSUE TITLE
webpack 3 + options + tsconfig.json

### ISSUE THREAD

**Issue by acopalipsis** [PatrickJS/starter#1905]
How to specify the path to tsconfig.json via options in webpack 3 ++?

```
// not work
use: [
    {
        loader: 'awesome-typescript-loader',
        options: {
            configFileName: './tsconfig.unit.json'
        }
    }
]
```
I have two configs `tsconfig.json` and `tsconfig.unit.json`. `tskonfig.json` intentionally contains an error. So when compiling, the console displays a message that the error in `tsconfig.unit.json`. Is bug. Error, this is an invalid option for the unit tests `"rootDir": "src"`

**Comment by ordinaryorange** [comment]
you need to use tsconfig-paths-webpack-plugin.  `new TsconfigPathsPlugin({configFile:"./tsconfig.tests.json"})` works for me. Check the docs.
