### ISSUE TITLE
jQuery(...).tooltip is not a function : jQuery included twice.

### ISSUE THREAD

**Issue by mahisha** [PatrickJS/starter#1906]
* **I'm submitting a ...**
[*] bug report

* **Do you want to request a *feature* or report a *bug*?**
Report a *bug*

* **What is the current behavior?**
In the build : jQuery included in both *bootstrap* and *main* JS bundle files.

* **Steps to reproduce**
Please check this commit : https://github.com/mahisha/angular-starter-bootstrap/commit/6ae501c88371d291f6b4bee07221310c8b5f072d
Repository : https://github.com/mahisha/angular-starter-bootstrap
Demo URL : https://mahisha.github.io/angular-starter-bootstrap/
Build files at : https://github.com/mahisha/angular-starter-bootstrap/tree/gh-pages

* **What is the expected behavior?**
jQuery should be included in only one bundle file.

* **Please tell us about your environment:**
Ubuntu + Angular 4.x + Chrome

**Comment by gabrielrb** [comment]
Hi @mahisha . 
Did you followed this tutorial?
https://github.com/AngularClass/angular-starter/wiki/How-to-include-jQuery

**Comment by mahisha** [comment]
@gabrielrb Thanks for the help. I tried to include null-loader. But the issue is somehow same jQuery.js file is loaded twice. I tried adding some console.log statements and found it is called twice.

I tried with earlier versions of angular-starter along with bootstrap-loader, which was working fine. But with the latest angular-starter + bootstrap-loader, I am getting this error.

Could you please help me in debugging this issue further, or any other suggestions to prevent loading jQuery twice.
