### ISSUE TITLE
How to re-bootstrap Angular Application?

### ISSUE THREAD

**Issue by DanielKucal** [PatrickJS/starter#1909]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X] question about the repository

* **Do you want to request a *feature* or report a *bug*?**
I want to know how to re-bootstrap Angular application, e.g. like shown here: https://github.com/angular/angular/issues/7009
I guess I should change something in `main.browser.ts` and `main.browser.aot.ts`, but I am not sure what and how...

* **What is the motivation / use case for changing the behavior?**
For now all instances of Angular components and services are kept in the memory when no longer needed - just new instances are created, nothing is cleared. I am able retrieve user data after he logs out of the application and this is a security hole. Re-bootstrapping the app should help...

* **Please tell us about your environment:**

- Angular version: 4.4.6
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
Here is my question about the main problem: https://stackoverflow.com/questions/46916785/angular-data-memory-leak-scoped-services-and-components-are-not-removed

Thanks in advance

**Comment by t-p-l-k** [comment]
How about reloading the page?

**Comment by DanielKucal** [comment]
@t-p-l-k, that's something I'd like to avoid

**Comment by kmandeville** [comment]
Any resolution for how to do this? I have logout functionality that logs a user out of our authentication provider and redirects to a logout success type page. That page has a link to log back in to the application. But this link doesn't trigger a full refresh of the angular application like clicking Refresh in the browser does. How can I go about triggering a full refresh of the application the next time the user comes back to the application when they logout?

**Comment by DanielKucal** [comment]
The ways to achieve it that I know about now:
1. `window.location.reload()`
2. Use redux store to have control over the data, I recommend NGXS.
3. Experiment with `platformBrowserDynamic().bootstrapModule(AppModule);` -  bootstrap app manually, keep the instance, then remove the instance and create new one.
