### ISSUE TITLE
When I am trying to run npm run server:dev --host abc.com, it is not loading correctly and getting Invalid host address

### ISSUE THREAD

**Issue by randeepnathtr** [PatrickJS/starter#1910]
We have to connect remote machine to get API access, but unable to connect it via --host 
Tried to include angular/cli but it is not working. Could you please help on this

**Comment by gabrielrb** [comment]
Hi @randeepnathtr . You're serving your api through http right? Why are you trying to use "npm run" to connect on that API? It's not easier to do a simple http call?
