### ISSUE TITLE
How can I turn on source maps for production? - Question

### ISSUE THREAD

**Issue by Olgagr** [PatrickJS/starter#1920]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ x] question

How can I turn on source maps for production? When I do ```npm run build:prod``` only source map for css file is generated. I know that this is done by default, however I would like to generate source maps for error handling tool.

**Comment by muehan** [comment]
in the webpack.pros.js check:
```
new UglifyJsPlugin({
        sourceMap: true,
...
```
and
```
new OptimizeJsPlugin({
        sourceMap: true
      }),

```
