### ISSUE TITLE
Hangs at 91% on an "additional asset processing" step 

### ISSUE THREAD

**Issue by alexw10** [PatrickJS/starter#1925]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[] bug report
[X] feature request
[X] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
This is an issue I believe with fairly larger projects. For ours it hangs awhile with the new Angular 5 setup.

Related is the issue:
https://github.com/webpack/webpack/issues/4558

It seems like some recent comments suggets that the UglifyJSplugin is the main problem?
Can that be removed? Or an alternative to it?

Any ideas?

* **What is the current behavior?**
Takes a really long time to do a production build.
Dev builds are fine.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
additional asset processing step should not take a long time

* **What is the motivation / use case for changing the behavior?**
Faster build

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by arrian0511** [comment]
I've encountered this issue also, as my countermeasure. I'd removed the "sourceMap: true" in UglifyJsPlugin and it works successfully.

**Comment by alexw10** [comment]
@arrian0511 thanks I'll give that a try.

**Comment by alexw10** [comment]
Even the dev environment takes a little bit sometimes and hands at like 90% when save changes etc... any one have ideas?

**Comment by arrian0511** [comment]
After investigating this issue, I've found out that the culprit why during AOT build is eating a lot of memory is because of this "ModuleConcatenationPlugin", try removing that one, and rebuild. hope this helps.

See this issue: https://github.com/webpack/webpack/issues/5992

**Comment by andreialecu** [comment]
There are various reports of this on the webpack issues board. I've been hit by it too in a fairly large angular project. 

It's related to `compress: true`, or more specifically to `unused` code optimization, in the UglifyJS plugin options.

Does anyone have a smaller repro that they could share with the UglifyJS team? See: 
https://github.com/mishoo/UglifyJS2/issues/2609

**Comment by xin1195** [comment]
Any ideas?

    What is the current behavior?
    Takes a really long time to do a production build.
    Dev builds are fine.

    If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via
    https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

    What is the expected behavior?
    additional asset processing step should not take a long time

    What is the motivation / use case for changing the behavior?
    Faster build

    Please tell us about your environment:

    Angular version: 2.0.0-beta.X
    Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

    Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by ramsunvtech** [comment]
Below settings helped me to reduce the heap memory since it will not include the sourceMap file.

```
devtool: false, // Webpack.

new webpack.optimize.UglifyJsPlugin({
   sourceMap: shouldUseSourceMap
}),
```

or below code will help for latest webpack uglify plugin.

```
> npm install uglifyjs-webpack-plugin --save-dev

// conf.js
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
module.exports = {
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        sourceMap: true,
      }),
    ],
  },
};
```

If this still not help to fix the problem. below command helps to increase heap memory and answer link to know more about heap memory is below as well.

```
node --max-old-space-size=16000 scripts/build.js
```

https://stackoverflow.com/a/57480923/1533666
