### ISSUE TITLE
svg-url-loader not working

### ISSUE THREAD

**Issue by gizm0bill** [PatrickJS/starter#1937]
any idea why this is not working with your latest webpack setup?
neither does svg-inline-loader or raw-loader for svgs.
the process passes through the loader code and it returns xml data, but at runtime a `require('to/some.svg')` ends up being a hash like this `e9223cdbd98ab53c4294606232cf160e.svg`

**Comment by gizm0bill** [comment]
Found the problem, it is the `file-loader` rule.
By the way, How would you use SVGs with this loader?

**Comment by bencameron00** [comment]
Hi, did you get your svgs to load? I'm facing the same problem.

**Comment by gizm0bill** [comment]
I used `raw-loader` instead

**Comment by bencameron00** [comment]
Cool, could you show me the webpack settings that you used to get it to load please?
