### ISSUE TITLE
Uncaught Error: Unexpected value 't' imported by the module 't'.

### ISSUE THREAD

**Issue by khalilof** [PatrickJS/starter#1947]
I just cloned the repo right now, and npm install and 
npm run build:prod
npm run server:prod

I get this in the browser :( 
Uncaught Error: Unexpected value 't' imported by the module 't'. Please add a @NgModule annotation.

**Comment by 1antares1** [comment]
The same... :/

**Comment by MADzO** [comment]
Check this #1921

**Comment by MartinMa** [comment]
Using `npm run build:aot:prod` instead **works** for now, but `build:prod` is still broken. No idea why.

System:
Windows 10 (fully patched)
npm 3.10.8
node v6.9.1

**Comment by MartinMa** [comment]
Fixed by https://github.com/gdi2290/angular-starter/commit/d35d537db16333938d322cebc2d3d493ec9a4ba6. ❤️
