### ISSUE TITLE
./node_modules/.bin/ng-xi18n fails

### ISSUE THREAD

**Issue by rkolec** [PatrickJS/starter#1952]
On clean angular-stater project: when I'm trying to generate translation file with ng-xi18n tool:
`./node_modules/.bin/ng-xi18n --i18nFormat xlf` 

I'm getting error:

`error TS2688: Cannot find type definition file for 'source-map'`

**Comment by MartinMa** [comment]
Same here. Could you find out how to solve this problem?

**Comment by zmnv** [comment]
Welcome Angular 5!

> If you rely on the date, currency, decimal, or percent pipes, in 5 you will see minor changes to the format. For applications using locales other than en-us you will need to import it and optionally locale_extended_fr from @angular/common/i18n_data/locale_fr and registerLocaleData(local).

[Angular Update Guide - 4.0 -> 5.0 for Advanced Apps](https://angular-update-guide.firebaseapp.com/)

### Also >>> [Angular and i18n](https://angular.io/guide/i18n)

Is it that?

Did you update angular-cli? https://github.com/angular/angular-cli/pull/8480

**Comment by MartinMa** [comment]
@zmnv Thanks for your quick answer. I double checked the update guide and couldn't find anything that's wrong. Well, the problem might be that I'm not using the CLI, but I'm trying to call the ng-xi18n binary directly (part of `@angular/compiler-cli` I think).

I end up doing the following as **workaround**.  I installed `@angular/cli` as dev dependency, added a *fake* `.angular-cli.json` with `"ejected": true` and called `ng xi18n`. Now it seems to work.

Using Angular 5.2.3 and Angular CLI 1.6.7.

**Comment by zmnv** [comment]
@MartinMa looks like shitty magic... 

did you try to just for your interest to compile a clean MASTER package of this repository with i18n ?

'cause this starter pack doesn't include Angular CLI not just for fan )))
