### ISSUE TITLE
Can not read configuration webpack

### ISSUE THREAD

**Issue by jindovu** [PatrickJS/starter#1957]
Hi Team
    Today I have just upgrade from angular 4 to angular version 5 base on angularClass, however I got issue and I don't know why it happen, please help me 
and this is error
![webpack](https://user-images.githubusercontent.com/19401173/34939522-a4fe2bde-fa1e-11e7-8579-6a01b2e2bb1c.png)

- **Resolved**: the folder contains project too deep, move on another folder it's working fine

**Comment by zmnv** [comment]
Obviously problem is in `index.html`. Dance from it to win!%)

**Comment by jindovu** [comment]
Thanks for reply, and this is my configuration 
[package.txt](https://github.com/gdi2290/angular-starter/files/1637581/package.txt)
