### ISSUE TITLE
Multiple bootstrappable entry points not supported for angular 5 with AoT

### ISSUE THREAD

**Issue by sedpro** [PatrickJS/starter#1961]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report (regression)
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
regression

* **What is the current behavior?**
NgcWebpackPlugin has a parameter mainPath, which forces build to have only one bootstrappable entry point. In former versions of this repo, there was no such parameter and I was able to make builds with multiple bootstappable entry points. 
They looked like 
```
export function main(): Promise<any> {
    return platformBrowserDynamic().bootstrapModule(SomeModule);
}
```

* **What is the expected behavior?**
We should be able to create as many bootstappable entry points as we need.

* **What is the motivation / use case for changing the behavior?**
By compiling a project in this way we can move common code to separate chunks using CommonChunkPlugin. Otherway we need to run compilation for each entry point (this takes a lot of time and several watch commands cannot be performed at the same time) and we cannot move common code to separate chunks (or I don't know how)

Maybe someone knows a solution to this issue?

* **Please tell us about your environment:**

- Angular version: 5.2.0
- Browser: [all]

**Comment by cristianmartinez** [comment]
Hey @sedpro, did you get any solution for this?

**Comment by cristianmartinez** [comment]
I think this issue belongs more to the `angular-cli` repository and there is an issue reported about this. You can follow it out at: https://github.com/angular/angular-cli/issues/7954

**Comment by sedpro** [comment]
@cristianmartinez , I have changed project to use single entrypoint with loading lazy-load modules. I have two apps(client and administrator), in both, I check if the user has permission to load this module.

**Comment by cristianmartinez** [comment]
Sounds like a really good solution, thank you!
