### ISSUE TITLE
Error when using tsconfig path

### ISSUE THREAD

**Issue by sutkovoy** [PatrickJS/starter#1962]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
*bug*

* **What is the current behavior?**

**tsconfig.webpack.json:**
`"@config/*":  ["src/app/config/settings/ll/*"],`

**settings.ts:**
```
export const settings = {
  'main_page_template_path': './ll/main-page.component.html',
};
```

**component.ts:**
```
import { settings } from '@config/settings.ts';
@Component({
  selector: 'main-page',
  template: settings.main_page_template_path,
  styleUrls:  ['main-page.component.scss'],
})
```
npm run clean:dist && npm run clean:aot && cross-env BUILD_AOT=1 npm run webpack -- --config config/webpack.prod.js --display-error-details  --progress --profile --bail"
```
  Parsed request is a module
  using description file: /Users/nik/data/x/package.json (relative path: ./src/app/modules/mainPage)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/nik/data/x/package.json (relative path: ./src/app/modules/mainPage)
    resolve as module
      looking for modules in /Users/nik/data/x/src
        using description file: /Users/nik/data/x/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
```

* **What is the expected behavior?**
Path should be found, app built.

* **Please tell us about your environment:**
node: v8.5.0
webpack: "3.5.3",

- Angular version: 4.3.2
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by zmnv** [comment]
How about 

"@config/*": ["**./**src/app/config/settings/ll/*"],

?)

**Comment by sutkovoy** [comment]
@zmnv, got an error: 
```
Starting compilation using the angular compiler.
Angular compilation done, starting webpack bundling.
Error: Error Substitution '**./**src/app/config/settings/ll/' in pattern '@config/' in can have at most one '*' character
```

**Comment by sutkovoy** [comment]
@gdi2290, please, help.

**Comment by sutkovoy** [comment]
How to use different tsconfig.json?

**Comment by zmnv** [comment]
Слушай, а не пробовал ?

```
import { settings } from '@config/settings.ts';
@Component({
  selector: 'main-page',
  template: './ll/main-page.component.html',
  styleUrls:  ['main-page.component.scss'],
})
```
где такой пример с конфигом нашел?

Потому что tsconfig.webpack.json
`"@config/*": ["src/app/config/settings/ll/*"],`

Это же для конструкции `import { module } from '@config/module'` только.
