### ISSUE TITLE
Not working on ie 11 getting error SCRIPT5022: Exception thrown and not caught

### ISSUE THREAD

**Issue by Naveendar** [PatrickJS/starter#1963]
I just downloaded the code and installed the NPM. It's working fine other browsers.
But getting error in ie : SCRIPT5022: Exception thrown and not caught
File: eval code (973), Line: 14, Column: 36.

**Comment by ravichandan** [comment]
solution is given in here [https://stackoverflow.com/a/45354411](https://stackoverflow.com/a/45354411)
