### ISSUE TITLE
Global environmental variables not resolving inside .forRoot, when building AOT

### ISSUE THREAD

**Issue by manolof** [PatrickJS/starter#1967]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

**This issue is observed when building with AOT**

When a developer is importing a module to the AppModule, with `.forRoot` and inserting arguments in it, if the arguments are coming from the global variables set in the webpack config files, then the value is `undefined`.

If I search the generated bundle file, I notice the following: `clientOptions:{clientID:void 0,domain:void 0}`

**My implementation of the module that has the `.forRoot` works when using it in an Angular CLI project**

* **If the current behavior is a bug, please provide the steps to reproduce.**

First, add a global variable inside `const METADATA` of the `webpack.prod.js` file, inside the `new DefinePlugin({})` of the `webpack.common.js`, and also inside the `custom-typings.d.ts`:

_webpack.common.js_ Ln. 176
```
new DefinePlugin({
	'ENV': JSON.stringify(METADATA.ENV),
	'HMR': METADATA.HMR,
	'AOT': METADATA.AOT,
	'AUTH_CLIENT_ID': JSON.stringify(METADATA.AUTH_CLIENT_ID),
	'AUTH_CLIENT_DOMAIN': JSON.stringify(METADATA.AUTH_CLIENT_DOMAIN),
	'process.env.ENV': JSON.stringify(METADATA.ENV),
	'process.env.NODE_ENV': JSON.stringify(METADATA.ENV),
	'process.env.HMR': METADATA.HMR
})
```

_webpack.prod.js_ Ln. 52
```
const METADATA = Object.assign({}, buildUtils.DEFAULT_METADATA, {
	host: process.env.HOST || 'localhost',
	port: process.env.PORT || 8080,
	ENV: ENV,
	HMR: false,
	AUTH_CLIENT_ID: '1234567890abc',
	AUTH_CLIENT_DOMAIN: 'https://example.com/auth',
});
```

Then, import your module into AppModule, and add the global environmental variables as arguments to its `forRoot`:
```
AuthModule.forRoot({
	clientOptions: {
		clientID: AUTH_CLIENT_ID,
		domain: AUTH_CLIENT_DOMAIN
	}
}),
```

* **What is the expected behavior?**
The global variables should be getting resolved during AOT build

* **What is the motivation / use case for changing the behavior?**
So that developers can pass arguments to their modules, with values coming from global environmental variables

* **Please tell us about your environment:**

- Angular version: ~5.0.1
- Browser: [Chrome 64]
- Node: 9.1.0
- npm: 5.5.1

**Comment by stormit-vn** [comment]
Do we have any update on this issue? I also encounter this problem, its working properly in development mode but ALL variables seem undefined with AOT build.

Note, the variables are defined if we use variable inside the constructor of an injectable provider i.e. service

```
import { Injectable } from '@angular/core';
import * as OktaSignIn from '@okta/okta-signin-widget';

@Injectable()
export class OktaService {
    private signIn;

    constructor() {
        this.signIn = new OktaSignIn({
            baseUrl: APP_CONFIG.okta.baseUrl,
            clientId: APP_CONFIG.okta.clientId
        });
    }
};
```

**Comment by stormit-vn** [comment]
I have fixed this issue by exporting another variable in the environment.prod.ts

```
export const ENV_APP_CONFIG: IAppConfig = APP_CONFIG;
```

Then we can explicit import this file from where we use the variables for configure module
```
import * as prodEnv from '../../environments/environment.prod';
export const oktaAuthConfig = {
    clientId: prodEnv.ENV_APP_CONFIG.OKTA_CLIENT_ID
    ....
};
```

Note, this just a workaround to temporary avoid hardcode the envionement variable. If anyone has any other ideas, please advise

**Comment by Dylan-TW** [comment]
I have the same issue. waiting for solutions
