### ISSUE TITLE
`npm run server:dev:hmr` error

### ISSUE THREAD

**Issue by iwxfer** [PatrickJS/starter#1969]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
When executing `npm run server:dev:hmr` an error is shown in web console, and application is not shown  

`Uncaught Error: [HMR] Hot Module Replacement is disabled.`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
Run with HMR without errors in JS console

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 5
- Browser: all

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by almothafar** [comment]
in package.json do you have `--hotOnly` or `--hot`, it must be `--hot` to replace  `--hotOnly`

**Comment by shelbymorris90** [comment]
@almothafar That fixed it for me. Suggest that change should be committed to the repo.

**Comment by adrhc** [comment]
I'm trying to use HMR the _gdi2290/angular-hmr_ or the _angular-cli_ way. None of them work, the page simply refreshes. Is HMR working with _gdi2290/angular-starter_ or not? There's any doc about how to use it?

**Comment by dvaldivia** [comment]
+1 @adrhc state used to be kept across reloads, but that is lost, any guidance on how to maintain the state would be good
