### ISSUE TITLE
$$_lazy_route_resource lazy recursive

### ISSUE THREAD

**Issue by radonirinamaminiaina** [PatrickJS/starter#1972]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @AngularClass](https://twitter.com/AngularClass)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
I got `TypeError: __webpack_require__.e is not a function` after trying to make a lazy load module.

* **My Code**

**_app-routing.module.ts_**
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Routes } from '@angular/router';

const routes: Routes = [
  { path: 'listes', loadChildren: 'app/component/list/list.module#ListModule'}
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes)
  ],
  declarations: [],
  exports: [ RouterModule ]
})
export class AppRoutingModule { }
```
**_list-routing.module.ts_**

```
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { ListComponent } from './list.component';

const routes: Routes = [] = [
  { path: '', component: ListComponent }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class ListRoutingModule { }
```
**_list.module.ts_**

```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { ListRoutingModule } from './list-routing.module';

import { ListComponent } from './list.component';

@NgModule({
  imports: [
    CommonModule,
    ListRoutingModule
  ],
  declarations: [ ListComponent ]
})
export class ListModule { }
```

* **Please tell us about your environment:**

- Angular version: 5.2.0
- Browser: all
- Angular cli:
```
@angular/cli: 1.7.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.5.3
webpack: 3.11.0
```

* **Other information** 
![image](https://user-images.githubusercontent.com/4496927/36592562-512d708a-18a7-11e8-84ba-09ec43c61867.png)

**Comment by lanovoy** [comment]
Seems like you have a typo here:

`const routes: Routes = [] = [
  { path: '', component: ListComponent }
];`

Should be:

`const routes: Routes = [
  { path: '', component: ListComponent }
];`
