### ISSUE TITLE
'rimraf' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by diepvv** [PatrickJS/starter#1997]
I run "npm start" and comandline throw error "'rimraf' is not recognized as an internal or external command" how can i fix?

**Comment by diepvv** [comment]
![image](https://user-images.githubusercontent.com/13696409/37750621-a01b2326-2dc0-11e8-9838-42e11d783a93.png)

**Comment by almothafar** [comment]
you just need to read the instructions in readme:

> npm install webpack-dev-server rimraf webpack -g to install required global dependencies

**Comment by lanovoy** [comment]
That's actually something that we might want to consider updating to be referenced from the local install. Since rimraf, webpack and webpack-dev-server are already listed as dependencies for angular-starter, their binaries (well, cmd's actually) are located under the ./node_modules/bin folder. So if we modify 
```bash
    "clean:dist": "rimraf dist",
```
to
```bash
    "clean:dist": "./node_modules/bin/rimraf dist",
```
It should work. I'm personally not a big fan of global dependencies...

**Comment by almothafar** [comment]
Well, `rimraf` is very helpful even for normal user use, and in 95% of all dependencies and project that I saw or used, using rimraf.

**Comment by lanovoy** [comment]
@almothafar Maybe, but in that case we should remove rimraf from dependencies, as there is really no point to have it installed both globally and locally, right?

**Comment by almothafar** [comment]
@lanovoy I think local one does not hurt, also, it can be helpful for running local version for deleting some folders like dist, but without global one deleting `node_modules` will be impossible if you run the local one.

**Comment by alanhg** [comment]
I have the same problem

**Comment by saiMedavarapu** [comment]
Delete the node modules folder and do npm install. That should work.

**Comment by jimmyFlash** [comment]
@VladimirRadeski suggestion
> rimraf is the UNIX command rm -rf for node.
> You need to install it with npm install rimraf -g.

solved it for me.
I have to say though, i'm not a fan of installing packages globally and also i have the it installed locally in my project

**Comment by furrybaer** [comment]
failed for me too.  Deleted node_modules folder, get error:  self signed certificate in certificate chain
