### ISSUE TITLE
How to SEO Angular Starter

### ISSUE THREAD

**Issue by nguyenthach16** [PatrickJS/starter#2000]
I used angular2-webpack-starter for my project. 
Main functions have been completed. Website can not SEO Google & Share Facebook OpenGraph.
I used Google chrome View page source 
...
<app>...</app> // data not found
....
I have watched and tested some angular SEO tutorial 2 but failed

Who has SEO success with angular2-webpack-starter please guide me

Thank you

**Comment by govi2010** [comment]
For SEO you need to use Server Side Rendering. It can be implemented but yet not implemented. 
I have done in past but currently I don't have access to code. I created 2 webpack file to one create server build and another to create client side build. 

for development we used existing webpack file.

**Comment by almothafar** [comment]
@govi2010 this is why contribution is the best things you can do before it is too late :)

**Comment by govi2010** [comment]
@almothafar  I always try my level best to do contribution on open source project. But as I mentioned I don't have access to code. Lets wait for angular 6 release I will try to create webpack which generate SSR package.

**Comment by SimpleCookie** [comment]
Sounds awesome @govi2010. I will save this thread, can you comment here once you get started/are done? I am interesting in following the development. 

I would be interested in watching while you do it if you do streaming, or pair programming.

**Comment by almothafar** [comment]
@govi2010 thank you very much, my comment was just a friendly note.

**Comment by govi2010** [comment]
@SimpleCookie  I am not that much expert that I can do it with live video sharing. Wait for Angular 6 I will surly implement it in this repo.

**Comment by SimpleCookie** [comment]
@govi2010 Neither am I, that's why I thought I could learn something from it 😄

**Comment by govi2010** [comment]
@gdi2290  Thank you for invitation.

**Comment by lanovoy** [comment]
@govi2010 Just FYI, even if you cannot push directly to some repo on github, you can always fork the repo, make the change and the create a pull request from your fork into the main repo.
Sorry for offtopic.

**Comment by govi2010** [comment]
@lanovoy  I will keep that in mind.

**Comment by kitolog** [comment]
Hi
Any updates there?

**Comment by govi2010** [comment]
@kitolog  I need basic idea what is needed. I am ready to implement as I know angular and webpack.
But I need requirements what should be included and what not.

**Comment by govi2010** [comment]
@Farqual  I will check your repository tomorrow.

**Comment by Farqual** [comment]
@govi2010 Thanks a lot, I will keep you updated if I make some progress on this !

**Comment by nimatullah** [comment]
Hello guys, I will be waiting for this feature.

**Comment by kitolog** [comment]
The simpliest and fastest way for me, was migrate all app sources to the Angular CLI, Angular 6 and integrate Angular Universal.
On the real and ready app it takes 1 - 2 days

**Comment by sumpton** [comment]
@kitolog me too. Conforming to Cli was the work, but letting it do all the magic was the best solution for us. The results are way better than I had hoped. Now, updates are a very simple command line. Something like

`ng update all`

will update Angular, Material, and rxjs and I don't need to worry about any configuration files for production.

We have a dozen domains sharing an api backend and a library for common code for the domains. I didn't expect Cli to be able to handle this complexity, but it is simple and the results amazing.

I have not yet integrated Universal.

**Comment by luizmacfilho** [comment]
Any updates?

**Comment by Farqual** [comment]
Okay so, after a few days trying to get Angular Universal working without using Angular CLI, I didn't succeed building a working server app with Webpack, so here is the simpliest solution I found (my app was based on this angular-starter) :

 - I installed this package : https://github.com/meltedspark/angular-builders/tree/master/packages/custom-webpack
 - Created a simple angular.json, which I used only to build the server part, because I wanted to keep building the browser part with my Webpack config, without Angular CLI.
 - Created a specific Webpack config file for server part (to extend the Angular CLI webpack config with the custom webpack angular builder).
 - Then you will juste have to add these lines in your package.json : 

```
"build:client-and-server-bundles": "npm run build:aot:prod && ng run patrivia:server --configuration=prod",
"webpack:server": "webpack --config config/webpack.server.config.js --progress --colors",
"build:ssr": "npm run build:client-and-server-bundles && npm run webpack:server",
"serve:ssr": "node dist/server",

```
 - Start with `npm run build:ssr && npm run serve:ssr`

Here is my angular.json : 

```
{
  "$schema": "./node_modules/@angular-devkit/core/src/workspace/workspace-schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "your-app": {
      "root": "",
      "projectType": "application",
      "architect": {
        "server": {
          "builder": "@angular-builders/custom-webpack:server",
          "options": {
            "customWebpackConfig": {
              "path": "config/webpack.server-bundle.config.js",
              "mergeStrategies": { "loaders": "replace" },
              "replaceDuplicatePlugins": true
            },
            "outputPath": "dist/server",
            "main": "src/main.server.ts",
            "tsConfig": "tsconfig.server.json"
          },
          "configurations": {
            "prod": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
            }
          }
        }
      }
    }
  },
  "cli": {},
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "app",
      "styleext": "scss"
    },
    "@schematics/angular:directive": {
      "prefix": "app"
    }
  }
}
```

This is working perfectly, and easy to set up, you have only two files to create in this starter : angular.json and webpack.server-bundle.config.js and one package to npm install (and the usual server.ts and webpack config file to compile it + [Angular Universal classic configuration](https://angular.io/guide/universal#preparation)).

Will post a repo with a working example based on angular-starter if some people wants it.

However, I'm still interested if someone finds a solution only with Webpack, without Angular CLI.

**Comment by nimatullah** [comment]
Any update guys?

**Comment by BruneXX** [comment]
Hi Guys, this is an issue for me too, do you have any news? thanks!

**Comment by BruneXX** [comment]
Hi @Farqual Do you have a repo with full solution coded?

**Comment by BruneXX** [comment]
Hi @govi2010 any update on this?
