### ISSUE TITLE
pseudo class :host not working for me

### ISSUE THREAD

**Issue by cfpperche** [PatrickJS/starter#2006]
**Note: for support questions, please use one of these channels:** [Chat: AngularClass.slack](http://angularclass.com/member-join/) or [Twitter: @TipeIO](https://twitter.com/TipeIO)

* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[x] others

* **What is the current behavior?**
How to do to make pseudo class :host works with angular-starter ?

I'm trying to do this and none of my components are applying styles with :host pseudo class

Thanks

**Comment by lanovoy** [comment]
What about @HostBinding() - does it work for you?

**Comment by cfpperche** [comment]
Yes, @hostBindings works fine, but if I define pseudo selector :host in my components styles or in sass components files doesn't . If I set component selector name the style is applied 

Eg

app-component { display: flex } works for me
:host { display: flex } doesn't 

Thanks
