### ISSUE TITLE
Unable to start with angular-starter

### ISSUE THREAD

**Issue by itsmeneartou** [PatrickJS/starter#2010]
* **I'm submitting a ...**
 bug report

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
I get an error when I start a server

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
i just used `npm run start` and `npm run server`

* **What is the expected behavior?**
The app development server should start

* **What is the motivation / use case for changing the behavior?**

I want to use angular-starter so I cloned the directory and used npm install. After all packages were installed I used `npm run start` and `npm run server` but it didn't worked.

* **Please tell us about your environment:**

- Angular version: 5.2.10
- Browser:N/A

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'server' ]
2 info using npm@3.10.10
3 info using node@v6.11.3
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle angular-starter@7.5.0~preserver: angular-starter@7.5.0
6 silly lifecycle angular-starter@7.5.0~preserver: no script for preserver, continuing
7 info lifecycle angular-starter@7.5.0~server: angular-starter@7.5.0
8 verbose lifecycle angular-starter@7.5.0~server: unsafe-perm in lifecycle true
9 verbose lifecycle angular-starter@7.5.0~server: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;F:\WebApps\angular-starter\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\GtkSharp\2.12\bin;F:\Cloud SDK\google-cloud-sdk\bin;C:\Program Files\Skype\Phone\;F:\Python\Python36-32\Scripts\;F:\Python\Python36-32\;C:\Users\abc\AppData\Local\Microsoft\WindowsApps;C:\Users\abc\AppData\Roaming\npm;flutter\bin;;C:\Program Files\Microsoft VS Code\bin
10 verbose lifecycle angular-starter@7.5.0~server: CWD: F:\WebApps\angular-starter
11 silly lifecycle angular-starter@7.5.0~server: Args: [ '/d /s /c', 'npm run server:dev' ]
12 silly lifecycle angular-starter@7.5.0~server: Returned: code: 1  signal: null
13 info lifecycle angular-starter@7.5.0~server: Failed to exec server script
14 verbose stack Error: angular-starter@7.5.0 server: `npm run server:dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid angular-starter@7.5.0
16 verbose cwd F:\WebApps\angular-starter
17 error Windows_NT 10.0.16299
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "server"
19 error node v6.11.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error angular-starter@7.5.0 server: `npm run server:dev`
22 error Exit status 1
23 error Failed at the angular-starter@7.5.0 server script 'npm run server:dev'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run server:dev
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by lanovoy** [comment]
Make sure you have latest NodeJs and npm installed.
