### ISSUE TITLE
some error when 'npm run  build:aot' and use echarts@3.8.5

### ISSUE THREAD

**Issue by ckmilse** [PatrickJS/starter#2025]
when I use 
`import * as echarts from 'echarts';
console.log(echarts);
` in 'src/polyfills.browser.ts'

and run 'npm run  build:aot'

there some error 
`ERROR in ./node_modules/echarts/lib/component/axis/AxisBuilder.js
Module build failed (from ./node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
Error: Debug Failure. False expression.`
and run 'npm run  build:prod'
is ok

* **Please tell us about your environment:**
mac 
node v9.2.0
angular-starter last commit 
`
commit b4eb96b2d3344a48f67e7d0f050c5aad74fc0948 (origin/master, origin/HEAD)
Author: PatrickJS <github@gdi2290.com>
Date:   Wed Jul 11 09:42:30 2018 -1000
`

Could you help me resolve this?

**Comment by ckmilse** [comment]
add one alias
 echarts: helpers.root('node_modules', 'echarts', 'dist', 'echarts.min.js')

**Comment by sankhlasaini** [comment]
I am getting the same issue Please Help

**Comment by sameerpallav** [comment]
I made it work with "outputHashing": "all", sourceMap: false in build config
