### ISSUE TITLE
Is this repository active?

### ISSUE THREAD

**Issue by matte00** [PatrickJS/starter#2053]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Is this repository active? Or there is same active fork with angular 7 support? etc etc?

**Comment by almothafar** [comment]
I think most of the people moved to Angular CLI, it has web pack internally, and with less work for scripting build scripts and so on.
I was using this until 5 and was planning to get Angular 6, but then that project is ended, and for the new projects it was only CLI.

**Comment by vladpopa33** [comment]
Does anyone has a guideline or a tool on how to migrate from this repo to Angular CLI?

**Comment by almothafar** [comment]
@vladpopa33 I think you will see a lot of guides around, but basically, it should be config files changes only, see https://medium.com/bratislava-angular/from-custom-webpack-build-to-angular-cli-9d87c3da6925

**Comment by matte00** [comment]
> I think most of the people moved to Angular CLI, it has web pack internally, and with less work for scripting build scripts and so on.
> I was using this until 5 and was planning to get Angular 6, but then that project is ended, and for the new projects it was only CLI.
> 
> Also, the Owner of this repo missing from like 3 months.

Thank you mate, i'll check Angular CLI. 
Have a nice day =)

**Comment by hoang-innomizetech** [comment]
All our previous projects using this starter kit (with some modifications), but today we are using https://github.com/nrwl/nx that also use Angular CLI to setup our full-stack projects. We also able to run custom webpack configuration using https://github.com/meltedspark/angular-builders/tree/master/packages/custom-webpack builder

**Comment by krawinkelm** [comment]
From my perspective I can not recommend to use this repo for your project setup. Working with a angular-cli based project is way more easy and safe for future.
Performing updates on depenencies costs way more time with this repo as with a angular-cli based repo.

Sorry but no recommendation from me.

**Comment by PatrickJS** [comment]
sry about that the real reason was because i was waiting for ivy I'll be updating the repo in the next month
