### ISSUE TITLE
What's going on with this repository?

### ISSUE THREAD

**Issue by envil** [PatrickJS/starter#2062]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x ] question about the decisions made in the repository

I see a lot of issues and PRs were closed without any resolution. What will happen with this repo? Is it dead? Should it be transferred to someone else?

**Comment by bryant-pham** [comment]
This repo is likely deprecated in favor of Angular CLI

**Comment by PatrickJS** [comment]
yes please use the angular cli for now. I'm making my own version but wont be ready til later

**Comment by PatrickJS** [comment]
sry about that the real reason was because i was waiting for ivy I'll be updating the repo in the next month
